on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Use GitHub Token
    steps:
      - uses: actions/checkout@v1
      - uses: ./
        with:
          token: '${{ secrets.SOMETHING_SECRET }}'
